app:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

server:
  port: 8095

spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://containers-us-west-68.railway.app:6368/railway
    username: postgres
    password: xhtTI10rPJkQvUXUpfVz
    driver-class-name: org.postgresql.Driver

service:
  client:
    filmService:
      url: http://localhost:8082

#eureka:
#  instance:
#    hostname: binar-cinema-discovery.up.railway.app
#  client:
#    serviceUrl:
#      defaultZone: https://${eureka.instance.hostname}/eureka